### ISSUE TITLE
BugsplatMac name doesn't follow new branding guidelines

### ISSUE THREAD

**Issue by bobbyg603** [BugSplat-Git/BugsplatMac#4]
If this is easy it would be nice to fix it when we release the new package with the HockeyApp upgrade. Joey just added a list of [brand guidelines](https://www.bugsplat.com/brand) that specifies all integrations should be BugSplat instead of Bugsplat. If this will break a lot of people's upgrade process then we should probably let it be.

**Comment by splatyourbugs** [comment]
Brand guidelines  should only be followed if they don’t break a bunch of peoples installs of our software.  Happy to have it stay Bugsplat.
